### ISSUE TITLE
Recommended additional intel to capture in B: Framework & Application Portfolio Summary

### ISSUE THREAD

**Issue by AlexanderRitchie** [bcgov/HADF-Overview#23]
Recommend that during the current state capture of the 1600+ applications that business capability(ies) of the applications is identified in the review of the applications - as is what business need(s) does the application deliver to users.

Alignment of capabilities will help define the future blueprint and can help with rationalization and informing of shared needs for common components as outlined in the Digital Framework and Digital Principles.

**Comment by RobertGoesByJim** [comment]
Alex, in a word, "Yes!"  Agree.  We have developed what we refer to as "archetypes", which you will find under Deliverable C / Business Applications.  They are a deviation of, but are not themselves, traditional "business capabilities".  I agree that recognizing that capability will facilitate modeling.

**Comment by CITZ-rwk** [comment]
@RobertGoesByJim  I've recently received some requests to update this site/content. Would suggest the main readme.md include a lifecycle badge to indicate the current state/condition.
