### ISSUE TITLE
 Compute section -> Containers -> The BC Gov Story - Needs reviewal

### ISSUE THREAD

**Issue by kusingh6** [bcgov/HADF-Overview#36]
The BC Gov Story
There are several applications being deployed in containers, as well as work is underway on **lifting and shifting applications** from legacy systems to the Openshift Platform.

I correct sense, you cannot lift & shift application running on VM's directly to Openshift. It requires **Replatforming or Refactoring** of the applications to host on the Openshift Container platform.

Please review.
Thanks!

**Comment by poornima-sivanand** [comment]
Thanks @kusingh6 : We have lifted and shifted a few applications before without refactoring them. so that is what i was trying to imply there.

**Comment by kusingh6** [comment]
You're somewhat correct @poornima-sivanand and it has to be re-platforming. As lift-n-shift implies to a VM export and not even changing any VM settings.

**Comment by poornima-sivanand** [comment]
Ithink maybe the term lift and shift means different things to different people. So valuable opinion.I will look at how I. can rephrase that. But i have worked with a team which was using the term lift and shift to move legacy apps to Openshift without making changes to them.

**Comment by poornima-sivanand** [comment]
Corresponds to PR-37 to fix this issue
