### ISSUE TITLE
Building a team page suggestions

### ISSUE THREAD

**Issue by HeatherRemacle** [bcgov/HADF-Overview#53]
Hey friends - there's lots more to say about "teams" that build digital products, and probably less you could say on this site. 

https://bcgov.github.io/HADF-Overview/ModernizationPlaybook/Business%20Applications/Product%20Approach/SelectingTheTeam.html

Teams require leadership and facilitation in addition to selecting talent. But I'm not sure this information belongs in HADF at all. There's ongoing work with the PSA to define, refine and guide organizations to foster "digital leadership" including building and supporting teams.

Ultimately, you aren't selecting a team, you are building one. Every time. So providing a short list of personality qualities is kind of misleading. (Though I wish it were that easy!)

You might reference how to procure or hire talent (e.g. sprint with us, code with us, and job store profiles - which are also under continuous improvement), and then point to the organizations or programs that are equipped to support doing this well.

Of course, these are just my 2 cents :)

**Comment by poornima-sivanand** [comment]
@HeatherRemacle : Thank you so much for your inputs. Will definitely incorporate them.

**Comment by CITZ-rwk** [comment]
@HeatherRemacle  @poornima-sivanand 

I was reviewing this recently, suggest a lifecycle badge be added/updated
