### ISSUE TITLE
Modern Web Application Components

### ISSUE THREAD

**Issue by cvarjao** [bcgov/HADF-Overview#61]
I prefer the [technology radar](https://www.thoughtworks.com/radar) approach to help developer pick technologies, while stay open to new things. Whenever possible focus on protocols/standards rather then specific tools.
Also, I would consider just simply endorsing the good work that [CNCF](https://landscape.cncf.io/) already do.

**Comment by poornima-sivanand** [comment]
@cvarjao : Thanks for the feedback. I will look into adding that. My only concern with cncf was whether it encompassed all the tools we are using or wanting to use. So we wanted to make it bcgov specific.

**Comment by ActionAnalytics** [comment]
This is exactly the same diagram I shared too, so I second the vote CNCF

**Comment by CITZ-rwk** [comment]
thank you for your comments
