### ISSUE TITLE
Re: scaleable

### ISSUE THREAD

**Issue by ashlinrichardson** [bcgov/HADF-Overview#64]
Please clarify all instances of use of term "scaleable", "scaleability" etc. to indicate which dimensions the organization is intended to be able to scale along, incl. but not limited to:
- internal profits / cost savings vs external profits / cost savings
- number of users per unit time
- number of site hits supported per unit time
- volume capacity of data stored
- velocity capacity of data processed
- variety of data sources utilized
- availability of technological diversity within the organization
- total RAM memory available to a given process
- total "cold" (magnetic HDD) storage available to a process
- total "hot" storage (e.g solid state device) available to a process
- number and type of GPGPU (graphics cards) available to a process

Many thanks
cheers

**Comment by CITZ-rwk** [comment]
thank you for your insight and comments
