### ISSUE TITLE
Re: physical servers

### ISSUE THREAD

**Issue by ashlinrichardson** [bcgov/HADF-Overview#65]
Dear Madam/ Sir at HADF, 

Several suggestions / feedback: 

Please consider to add:
* fixed price assets mitigate risk of cost overruns and/or budget evaporation associated w rented or pay-as-you-go assets
* physical security of your hardware is necessary (but not sufficient) for information security. For enhanced security applications (incl. but not limited to Law Enforcement and/or other sensitive application areas w Personally Identifiable Information) it's a best practice to control the physical security of hardware on which information resides
* the flexibility of owned assets mitigates the risk of lack of fit for purpose
* situational awareness: physical servers allow us to know what we have and where they are.  If we're not using physical servers we don't 100% know what we're using, where it is, or even how much we're paying per unit of resource capacity

Please remove "initial cost of ownership and maintenance of Physical Servers is very high" unless it's possible to quantify "how high" and in relation to what other options. With automation, maintenance of server farms can be increasingly cost effective. 

What if investment in physical servers isn't a con at all, if it's a hedge against budget-evaporation / cost overrun type risks involved with pay-as-you-go (or other "nonphysical") type contracts? Please reference balancing risk of fixed price assets being underutilized vs. risk of non-fixed price assets being over-utilized

Please add incremental distributed options to "Physical Servers", e.g. a number of  the organization's technology capacity issues could be solved by repurposing (e.g. in an unstructured or semi-structured distributed system) idle capacity on existing "nonserver"/ desktop or even mobile computing systems assets, without additional costs to procure new systems

Please remove or heavily revise 4. "Each application normally resides on three servers or environments" because the topic of potential  configuration drifts between environments, which can / should be mitigated by using modern version control practices, should be independent of whether the organization owns the technology assets

Please remove the statement "Physical servers do not typically share resources with each other in a data center thereby limiting the number of applications that can be housed on them" as this is not the case in most contemporary organizations. From the perspective of graduate studies in computing science completed, lack of resource sharing is usually entirely related to software  choices, as opposed to financial decisions around hardware,  asset ownership or lack thereof

Many thanks for considering these suggestions
cheers

Ashlin

**Comment by CITZ-rwk** [comment]
This is very valuable feedback and we will look to incorporate this in our next release, thank you
